model_params:
  name: 'BetaVAE'
  in_channels: 1
  in_length: 256
  latent_dim: 32
  kld_weight: 0.5
  LR: 0.0005
  beta: 4
  loss_type: 'H'
  weight_decay: 0.00095
  scheduler_gamma: .98

logging_params:
  save_dir: "logs/"
  name: 'BetaVAE_InVivoRaw'

exp_params:
  manual_seed: 1111

data_params:
  data_path: '/home/matt/data/InVivoLFPs/BLA_LFP_data/Part2SubjectHB15_AW.mat'
#  '/home/matt/data/InVivoLFPs/BLA_LFP_data/LFP_BLA_gamma.mat'
#  "/home/matt/data/InVivoLFPs/FengData/LFP_elec_combine.txt"
  train_batch_size: 16
  val_batch_size: 16
  filter_type: 'raw'
  filter_rate: 50  # stride for samples
  only_bursts: False

trainer_params:
  gpus: 1
  max_epochs: 20